[build]
  # Diretório de build
  publish = "dist"
  
  # Comando para build de produção
  command = "npm run build"
  
  # Diretório das functions serverless
  functions = "functions"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"
  
  # Variáveis de ambiente necessárias para o build
  VITE_SUPABASE_URL = "https://gjvtncdjcslnkfctqnfy.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqdnRuY2RqY3NsbmtmY3RxbmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzM0MDEsImV4cCI6MjA1OTU0OTQwMX0.AzALxUUvYLJJtDkvxt7efJ7bGxeKmzOs-fT5bQOndiU"
  VITE_BRAPI_API_KEY = "iM7qSWmznjW7iNPwMEoAK4"
  VITE_ALPHA_VANTAGE_API_KEY = "7KAUW1MTXT6TPCKU"
  VITE_FINNHUB_API_KEY = "cvu1cmhr01qjg136up40cvu1cmhr01qjg136up4g"

# Redirecionamentos para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configurações para arquivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"