name: Deploy to Supabase

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  SUPABASE_PROJECT_ID: gjvtncdjcslnkfctqnfy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run type check
        run: npm run type-check
      
      - name: Run linter
        run: npm run lint
      
      - name: Build application
        run: npm run build
      
      - name: Setup Supabase CLI
        uses: supabase/cli-action@v1
        with:
          access-token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
      - name: Push database migrations
        run: npx supabase db push --project-id ${{ env.SUPABASE_PROJECT_ID }}
      
      - name: Deploy Edge Functions
        run: |
          npx supabase functions deploy execute-command --project-id ${{ env.SUPABASE_PROJECT_ID }}
          npx supabase functions deploy cognitive-core --project-id ${{ env.SUPABASE_PROJECT_ID }}
          npx supabase functions deploy ingest-market-data-cron --project-id ${{ env.SUPABASE_PROJECT_ID }}
          npx supabase functions deploy sentinel-agent-cron --project-id ${{ env.SUPABASE_PROJECT_ID }}
          npx supabase functions deploy test-cognitive --project-id ${{ env.SUPABASE_PROJECT_ID }}
      
      - name: Deploy status
        if: always()
        run: |
          echo "Deploy completed with status: ${{ job.status }}"